### ISSUE TITLE
FUAM - showing same details for all capacities

### ISSUE THREAD

**Issue by alexisjensennz** [microsoft/fabric-toolbox#183]
Hi,

I have just deployed version 2025.7.1. in the capacity utilization tab, I am getting the same results for all 3 capacities.  Is this a known bug?

<img width="1451" height="649" alt="Image" src="https://github.com/user-attachments/assets/ea973fae-3b1e-4ae5-a367-15b662761710" />

**Comment by kethom-analytics** [comment]
@alexisjensennz We will check it immediately

**Comment by ggintli** [comment]
Dear @alexisjensennz,

thanks for reporting that. One line was missing in the notebook.

Now we fixed the issue, please find the changelog below:
https://github.com/microsoft/fabric-toolbox/blob/main/monitoring/fabric-unified-admin-monitoring/changelog/FUAM_Changelog.md#-changelog--fuam-release-202572

**Fix lakehouse data for your FUAM instance:**

1. Rerun the "Deploy_FUAM notebook"

2.  For you case can you please run one time the "Load_FUAM_Data_E2E" pipeline today with following parameter:
metric_days_in_scope = 14

**Affect:** It will overwrite the last 14 days capacity metrics data in your Lakehouse with the corrected values.

3. After that you can schedule this pipeline e.g. on daily basis with parameter metric_days_in_scope = 2 (normal incremental load).

-------------
I hope it helps! Please let me know if that worked for you, I keep this issue open until your response :)

Best Regards,
Gellert

**Comment by AJGOLD062025** [comment]
Hi @ggintli , 
what is the issue exactly? I have just installed what I believe is FUAM Release 2025.7.1 but I do not see any issues with my capacity data? I have the following parameters:

<img width="816" height="825" alt="Image" src="https://github.com/user-attachments/assets/aa95df29-475c-47a1-bc50-4f9296f83fb1" />

Do I still need to update again? The report is showing an update is available annoyingly

**Comment by vanessakion** [comment]
It looks like the current release isn't updating after redeployment of 2025.7.2, so I'm still seeing the “update is available” message.

**Comment by alexisjensennz** [comment]
Can you please confirm new notebook is available.  I downloaded what I thought was the latest version but I still get it showing 2025.7.1 and same capacities issue.

**Comment by ggintli** [comment]
Hello,

we close this issue, since a new version of FUAM has been deployed.

Please find the change log from FUAM here: https://github.com/microsoft/fabric-toolbox/blob/main/monitoring/fabric-unified-admin-monitoring/changelog/FUAM_Changelog.md

"How to update FUAM" here:
https://github.com/microsoft/fabric-toolbox/blob/main/monitoring/fabric-unified-admin-monitoring/how-to/How_to_update_FUAM.md

Best Regards,
ggintli
